apiVersion: v1
kind: Pod
metadata:
  name: mssql-server
  labels:
    app: mssql-server
spec:
  containers:
    - name: mssql
      image: mcr.microsoft.com/mssql/server:2022-latest
      ports:
        - containerPort: 1433
      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "mypasswordA@"
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  type: NodePort
  selector:
    app: mssql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433


#CREATE DATABASE MyDatabase;
#GO

  CREATE TABLE log (
  EmployeeID INT PRIMARY KEY IDENTITY(1,1),
  FirstName NVARCHAR(50),
  LastName NVARCHAR(50),
  Age INT,
  Email NVARCHAR(100) UNIQUE,
  HireDate DATETIME DEFAULT GETDATE()
  );
  GO