---
- name: Create jobs for Linux and Windows hosts
  hosts: all
  become: yes
  tasks:
    - name: "Create job on Linux hosts"
      block:
        - name: "Generate cron job script from template"
          template:
            src: linux_cron_job.j2
            dest: "{{ path_job }}/{{ item.name }}_cron.sh"
            mode: '0755'
          loop: "{{ service }}"
          when: ansible_connection == 'ssh'

        - name: "Ensure cron job is present on Linux"
          cron:
            name: "{{ job_name }} for {{ item.name }}"
            minute: "0"
            hour: "0"  # Daily job at midnight
            day: "*"
            month: "*"
            weekday: "*"
            job: "{{ path_job }}/{{ item.name }}_cron.sh"
          loop: "{{ service }}"
          when: ansible_connection == 'ssh'

        - name: "Create backup directories if needed"
          file:
            path: "{{ item.backup_path | default(item.path + '/backup') }}"
            state: directory
            mode: '0755'
          loop: "{{ service }}"
          when: ansible_connection == 'ssh' and item.backup

    - name: "Create job on Windows hosts"
      block:
        - name: "Generate PowerShell script for scheduled task from template"
          template:
            src: windows_scheduled_task.j2
            dest: "{{ path_job }}\\{{ item.name }}_cleanup.ps1"
          loop: "{{ service }}"
          when: ansible_connection == 'winrm'

        - name: "Ensure scheduled task is present on Windows"
          win_scheduled_task:
            name: "{{ job_name }}_{{ item.name }}"
            description: "Cleanup job for {{ item.name }} service logs"
            actions:
              - path: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
                arguments: "-File {{ path_job }}\\{{ item.name }}_cleanup.ps1"
            trigger:
              - schedule: daily
                start_boundary: "00:00:00"  # Daily job at midnight
            username: "SYSTEM"
            state: present
          loop: "{{ service }}"
          when: ansible_connection == 'winrm'

        - name: "Create backup directories on Windows if needed"
          win_file:
            path: "{{ item.backup_path | default(item.path + '\\backup') }}"
            state: directory
          loop: "{{ service }}"
          when: ansible_connection == 'winrm' and item.backup

        - name: "Schedule backup jobs on Windows"
          win_scheduled_task:
            name: "Backup_{{ job_name }}_{{ item.name }}"
            description: "Backup job for {{ item.name }} service logs"
            actions:
              - path: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
                arguments: "-Command 'Copy-Item -Path {{ item.path }}\\* -Destination {{ item.backup_path | default(item.path + '\\backup') }} -Recurse'"
            trigger:
              - schedule: daily
                start_boundary: "00:00:00"  # Daily backup at midnight
            username: "SYSTEM"
            state: present
          loop: "{{ service }}"
          when: ansible_connection == 'winrm' and item.backup
