#!/bin/bash

# Check if ip.txt file exists
if [ ! -f "ip.txt" ]; then
    echo "ip.txt file not found!"
    exit 1
fi

# Loop through each IP in ip.txt
while IFS= read -r ip; do
    # Skip empty lines and comments
    if [[ -z "$ip" || "$ip" == \#* ]]; then
        continue
    fi
    
    # Check if port 22 (SSH) is open
    nc -z -v -w5 "$ip" 22 &> /dev/null
    if [ $? -eq 0 ]; then
        echo "$ip linux"
    else
        # If port 22 is closed, check port 3389 (RDP for Windows)
        nc -z -v -w5 "$ip" 3389 &> /dev/null
        if [ $? -eq 0 ]; then
            echo "$ip windows"
        else
            echo "$ip"
        fi
    fi
done < "ip.txt"
